services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
# Use Docker volumes when you want the Docker Engine to manage the storage volume.
# Define Docker volumes for persistent storage
volumes:
  grafana-storage: {}