services:
  
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    # restart: unless-stopped
    restart: "no"
    ports:
      - '3000:3000'

    environment:
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_SECURITY_COOKIE_SECURE: "false"
    volumes:
      # Save Grafana data (dashboard, utsers) so we don't loses with reboot
      - grafana-storage:/var/lib/grafana
      # mount custom dir host inside Grafana container (ro=read only)
      - /opt/machineinnovation/db:/opt/machineinnovation/db:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
# Use Docker volumes when you want the Docker Engine to manage the storage volume.
# Define Docker volumes for persistent storage
volumes:
    grafana-storage: {}
