name: Machine Innovation Monitoring 

on:
  push:
    branches: 
      - "main"
    paths:
      # si attiba solo se sono i modificati i files
      - 'src/outputs-baseline-prod/*.db'
      - 'src/outputs-baseline-prod/*.png'
      - 'src/outputs-baseline-debug/*.db'
      - 'src/outputs-baseline-debug/*.png'
      
  workflow_dispatch:
    inputs:
      mode:
        description: "Seleziona la modalità di esecuzione (demo o prod)"
        default: "demo"
        type: choice
        options:
          - "demo"
          - "prod"

permissions:
  contents: write

jobs:
  render-charts:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # 2. Configura i permessi ed esegui lo script del DB
      - name: Esegui install_db.sh e aggiorna il db
        run: |
          chmod +x ./install_db.sh
          if [ "${{ github.event.inputs.mode }}" = "prod" ]; then
            echo "install db in modalità PRODUCTION..."
            sudo ./install_db.sh src/outputs-baseline-prod/metrics.db
          else
            echo "install db in modalità DEMO..."
            sudo ./install_db.sh src/outputs-baseline-debug/metrics.db
          fi

          sudo chmod -R 777 /opt/machineinnovation/

      # 3. Avvia Grafana
      - name: Avvia Grafana
        working-directory: ./monitoring
        run: docker compose up -d grafana

      # 4. Attendi che Grafana sia pronto stabilmente
      - name: Wait start
        run: sleep 60
    
      - name: Wait Grafana Loop
        run: |
          MAX_RETRY=30
          RETRY=0

          until curl -s http://localhost:3000/api/health | grep -q '"database": "ok"'
          do
            RETRY=$((RETRY+1))

            echo "Tentativo ${RETRY}/${MAX_RETRY}: Grafana non pronta"

            if [ $RETRY -ge $MAX_RETRY ]; then
              echo "ERRORE: timeout attesa Grafana"
              exit 1
            fi

            sleep 5
          done

          echo "Grafana pronta"

      # 6. Configura l'ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
          cache: 'pip'

      # 7. Installa Playwright e Chromium
      - name: Installa dipendenze e Playwright
        run: |
          pip install playwright 
          playwright install chromium --with-deps

      # 9. Rimuove le vecchie immagini e cattura i nuovi Screenshot
      - name: Catch Screenshot Dashboard
        run: |
          rm -f ./images/dashboard_table.png
          rm -f ./images/dashboard_timeseries.png
          python ./monitoring/rend_dashboard_panel.py
        
      # 10. [DEBUG] Verifica i percorsi di output
      - name: Debug Images check
        run: |
          echo "=== Contenuto della Root ==?"
          ls -lrt
          echo "=== Contenuto di ./images/ ==="
          ls -lrt ./images/ || true
          echo "=== Contenuto di ./monitoring/ ==="
          ls -lrt ./monitoring/ || true
        
      - name: Estrai ultima metrica e salva JSON
        run: |
          sqlite3 -json /opt/machineinnovation/db/metrics.db "
          SELECT accuracy, precision, recall, f1_score
          FROM model_metrics_baseline
          LIMIT 1000;
          " > ./monitoring/all_metrics.json

      - name: Estrai ultima metrica e salva JSON
        run: |
          sqlite3 -json /opt/machineinnovation/db/metrics.db "
          SELECT accuracy, precision, recall, f1_score
          FROM model_metrics_baseline
          WHERE timestamp = (SELECT MAX(timestamp) FROM model_metrics_baseline)
          LIMIT 1;
          " > ./monitoring/latest_metrics.json

      # [DEBUG] Verifica che il file JSON sia stato creato correttamente
      - name: Mostra JSON generato
        run: cat ./monitoring/latest_metrics.json

      # 11. Spegni i container Docker 
      - name: Stop Docker
        working-directory: ./monitoring
        run: docker compose down

      # 12. Commit e Push sul repository
      - name: Commit + Push of the update graph 
        run: |
          git config --local user.name "francescofrigerio"
          git config --local user.email "francesco.frigerio@greencore.it"
          git add ./images/dashboard_table.png
          git add ./images/dashboard_timeseries.png
          git add ./monitoring/latest_metrics.json

          # le immagini png possono essere modificate 
          # di poco ad ogni esecuzione
          # per evitare salvataggi inutili e sistematici
          # esegue il seguente controllo
          if git diff --cached --quiet; then
             echo "Nessuna modifica alle immagini"
             exit 0
          fi

          git commit -m "Auto: Aggiornato grafico di training [skip ci]" || exit 0
          git push
          # dopo ogni commit automatico fare un git pull
          # ad ogni partenza del codespace 