name: Machine Innovation CI CD Pipeline

on:
  push:
    branches:
      - "main"
    
  pull_request:
    branches: 
      - "main"

  # Avviaamento manuale solo per la versione demo (vedere file deployment.md)
  # da verificare l'esecuzione schedulata con airflow (una volta al mese oppure settimana)
  workflow_dispatch:

permissions:
  # da verificare
  # contents: read
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test with pytest 
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        working-directory: "."
        run: |
          chmod +x ./run_test_ci.sh
          ./run_test_ci.sh

  # viene eseguito solo se il job
  # di test ha successo.
  train:
    needs: test
    # il train viene eseguito solo sul branch di main
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run train
        env:
          HF_TOKEN_WRITE: ${{ secrets.HF_TOKEN_WRITE }}
        run: |
          chmod +x ./run_train_prod.sh
          # esegue in modalita demo 
          # perchè il progetto possa essere
          # visionato in tempi rapidi (35 minuti)
          # Documentato dentro pipeline-deplyment-cicd.md
          ./run_train_prod.sh --demo
          # Salva il percorso corretto nel file d'ambiente di GitHub Actions
          echo "MODEL_OUT_DIR=src/outputs-baseline-debug" >> $GITHUB_ENV
          

      # se il train ha successo il modello viene
      # caricato su repository tipo model di Hugging Face
      - name: Upload Model to Hugging Face
        env:
          HF_TOKEN_WRITE: ${{ secrets.HF_TOKEN_WRITE }}
        run: |
          python ci_cd/CD/hf_deploy.py

      # === INVIA IL CODICE DI SERVING ALLO SPACE DI HUGGING FACE ===
      - name: Deploy to Hugging Face Spaces
        env:
          HF_TOKEN_WRITE: ${{ secrets.HF_TOKEN_WRITE }}
        run: |
          # Configura Git con un utente fittizio
          git config --global user.email "francesco.frigerio@greencore.it"
          git config --global user.name "francescofrigerio"
          
          # Clona lo Space di Hugging Face in una cartella temporanea usando il tuo Token
          # Sostituisci "NOME_UTENTE" e "NOME_SPACE" con i tuoi dati reali
          git clone https://x:$HF_TOKEN@huggingface.co/spaces/francescofrigerio/spacemachineinnovatorsmlops hf_space
          
          # Svuota la cartella dello Space (tranne i file Git) e copia il nuovo contenuto di model_serving
          rm -rf hf_space/*
          cp -r model_serving/* hf_space/
          
          # Invio delle modifiche. 
          # Hugging Face fa ripartire lo Space in automatico
          cd hf_space
          git add .
          git diff-index --quiet HEAD || git commit -m "Deploy automatico da GitHub Actions"
          git push origin main
          
      - name: Build model_serving with Dockerfile
        run: |
          docker build -f model_serving/Dockerfile -t machine-innovation-serving:latest ./model_serving

